FROM debian:stable-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg gpg \
    rsync bash wget \
    coreutils findutils \
    aptly \
    python3 python3-yaml \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /work
